services:
    chris1278.statblockbridge.controller.acp:
        class: chris1278\statblockbridge\controller\acp_controller
        arguments:
            - '@ext.manager' 
            - '@config'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
    chris1278.statblockbridge.listener:
        class: chris1278\statblockbridge\event\listener
        arguments:
            - '@ext.manager'
            - '@config'
            - '@template'
            - '@log'
            - '@user'
            - '@language'
        tags:
            - { name: event.listener }
